### PR TITLE
Factor out debug tables

### PR DESCRIPTION
**Pull request by mrkickling**
- Factor out into separate method
- Make sure it is only calculated on debug logging level

### CODE REVIEW

**Comment by andrewbwm** [comment]
Looks good, I suspect you're already working on this, but I'll add it as a reminder just in case. We should also rework the string formatting so that it uses c-type printing instead of the format() str method.

**Comment by mrkickling** [comment]
Yes, and I actually postponed it at this time (#62) because it feels too messy to do it while we refactor other stuff in malsim.

**Comment by andrewbwm** [comment]
> Yes, and I actually postponed it at this time (#62) because it feels too messy to do it while we refactor other stuff in malsim.

Yes, I saw that, and that makes sense, but you should have the ones specifically used with format_table match the preferred type.

**Comment by mrkickling** [comment]
I looked into it, but since headers are strings and not the values, it becomes problematic. Also "%-5d %-80s %-6d %-5d %-5d %-5s %-5d %s\n" is not more readable than the alternative .. maybe for the table creation using the .format is not actually that bad?

**Comment by andrewbwm** [comment]
> I looked into it, but since headers are strings and not the values, it becomes problematic. Also "%-5d %-80s %-6d %-5d %-5d %-5s %-5d %s\n" is not more readable than the alternative .. maybe for the table creation using the .format is not actually that bad?

Ok, we can leave it as a separate issue an look into it when we fix the entire logging.

**Comment by mrkickling** [comment]
Then I will merge if that is alright for you

**Review by andrewbwm — APPROVED** [review]

**Pull request merged**
