### PR TITLE
Action mask is a tuple of arrays

### PR DESCRIPTION
**Pull request by kasanari**
This is the format Space.sample expects.

### CODE REVIEW

**Comment by andrewbwm** [comment]
This is a fix for #7, correct?

**Comment by kasanari** [comment]
That is true. I forgot I had made the issue.

**Comment by mrkickling** [comment]
Should be straight forward to merge this right?

**Comment by andrewbwm** [comment]
Was squash-merged in 458edc890dbd2fd9602a0c76e12c9f2bc2273637.

**Pull request closed without merging**
